import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ToastProvider, useToast } from './context/ToastContext';
import { AuthProvider, useAuth } from './context/AuthContext';
import { LoginView } from './components/LoginView';
import { Navbar } from './components/Navbar';
import { BottomNav, TabType } from './components/BottomNav';
import { HomeTab } from './components/HomeTab';
import { AttendanceTab } from './components/AttendanceTab';
import { SalesTab } from './components/SalesTab';
import { PayslipsTab } from './components/PayslipsTab';
import { ProfileTab } from './components/ProfileTab';
import { LeaveModal } from './components/LeaveModal';
import { ref, get, push, set, query, orderByChild, equalTo, serverTimestamp } from 'firebase/database';
import { db } from './lib/firebase';

const MainPortal: React.FC = () => {
  const { currentUser, userEmail, userName, userEmpId, staffProfile, isAuthorized, loading } = useAuth();
  const { showToast } = useToast();

  const [activeTab, setActiveTab] = useState<TabType>('home');
  const [isLeaveModalOpen, setIsLeaveModalOpen] = useState(false);

  // Auto-absent check if past 11:00 AM and no attendance was logged today
  useEffect(() => {
    if (!userEmail) return;

    // Wait for the staff profile to load so the record always carries the
    // real staff name (from the 'staff' database), not a placeholder.
    if (!staffProfile) return;

    const checkAutoAbsent = async () => {
      const now = new Date();
      const currentMinutes = now.getHours() * 60 + now.getMinutes();
      const time1100AM = 11 * 60;
      const todayISO = now.toISOString().split('T')[0];

      if (currentMinutes <= time1100AM) return;

      const normalizedEmail = userEmail.toLowerCase();
      const staffName = staffProfile.name || userName;

      try {
        // Query only this staff member's attendance records instead of
        // downloading the entire attendance_logs table.
        const staffLogsQuery = query(
          ref(db, 'attendance_logs'),
          orderByChild('userEmail'),
          equalTo(normalizedEmail)
        );
        const snap = await get(staffLogsQuery);

        let alreadyLogged = false;
        if (snap.exists()) {
          const logs = snap.val();
          for (const k in logs) {
            if (logs[k]?.date === todayISO) {
              alreadyLogged = true;
              break;
            }
          }
        }

        // Only push an ABSENT record if this staff member has no attendance
        // logged for today. If one already exists, skip the push entirely.
        if (alreadyLogged) return;

        const newLogRef = push(ref(db, 'attendance_logs'));
        await set(newLogRef, {
          id: newLogRef.key,
          empName: staffName,
          empId: userEmpId,
          userEmail: normalizedEmail,
          date: todayISO,
          clockIn: '--:--',
          clockOut: '--:--',
          durationMs: 0,
          durationText: '0h 0m',
          punctualityStatus: 'ABSENT',
          statusColor: 'red',
          autoGenerated: true,
          createdAt: serverTimestamp(),
        });
        showToast('Notice: You have been marked ABSENT for today (past 11:00 AM).', 'error', 'Punctuality Notice');
      } catch (e) {
        console.warn('Auto-absent check:', e);
      }
    };

    checkAutoAbsent();
  }, [userEmail, userName, userEmpId, staffProfile]);

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-[#0F172A] text-white">
        <div className="flex flex-col items-center gap-3">
          <div className="w-8 h-8 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
          <span className="text-xs text-slate-400 font-medium tracking-wide">Loading Hemzal Staff Portal...</span>
        </div>
      </div>
    );
  }

  if (!currentUser || !isAuthorized) {
    return <LoginView />;
  }

  return (
    <div className="min-h-screen flex flex-col bg-[#0F172A] text-slate-300 selection:bg-blue-600 selection:text-white pb-24 font-sans">
      {/* Top Navbar */}
      <Navbar />

      {/* Main Tab Content View */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6 flex-1 w-full">
        <AnimatePresence mode="wait">
          {activeTab === 'home' && (
            <motion.div
              key="home"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
            >
              <HomeTab onOpenLeaveModal={() => setIsLeaveModalOpen(true)} />
            </motion.div>
          )}

          {activeTab === 'attendance' && (
            <motion.div
              key="attendance"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
            >
              <AttendanceTab onOpenLeaveModal={() => setIsLeaveModalOpen(true)} />
            </motion.div>
          )}

          {activeTab === 'sales' && (
            <motion.div
              key="sales"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
            >
              <SalesTab />
            </motion.div>
          )}

          {activeTab === 'payslip' && (
            <motion.div
              key="payslip"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
            >
              <PayslipsTab />
            </motion.div>
          )}

          {activeTab === 'profile' && (
            <motion.div
              key="profile"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -8 }}
              transition={{ duration: 0.15 }}
            >
              <ProfileTab />
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      {/* Leave Application Modal */}
      <LeaveModal isOpen={isLeaveModalOpen} onClose={() => setIsLeaveModalOpen(false)} />

      {/* Fixed Bottom Navigation */}
      <BottomNav activeTab={activeTab} onTabChange={(tab) => setActiveTab(tab)} />
    </div>
  );
};

export default function App() {
  return (
    <ToastProvider>
      <AuthProvider>
        <MainPortal />
      </AuthProvider>
    </ToastProvider>
  );
}
