export interface StaffProfile {
  key?: string;
  name: string;
  email: string;
  phone?: string;
  position?: string;
  branch?: string;
  status?: 'ACTIVE' | 'INACTIVE' | string;
  createdAt?: number;
}

export interface Branch {
  key?: string;
  name: string;
  code?: string;
  status?: 'ACTIVE' | 'INACTIVE' | string;
  address?: string;
}

export interface GeoLocationPoint {
  lat: number | null;
  lng: number | null;
  status: 'SUCCESS' | 'FAILED' | 'PENDING';
  error?: string;
  accuracy?: number;
}

export interface AttendanceLog {
  id?: string;
  key?: string;
  empName: string;
  empId?: string;
  userEmail: string;
  date: string; // YYYY-MM-DD
  clockIn: string; // HH:mm
  clockOut: string; // HH:mm
  durationText?: string;
  durationMs?: number;
  punctualityStatus?: 'ON TIME' | 'LATE' | 'ABSENT' | 'LEAVE' | 'MC' | 'OFF' | string;
  statusColor?: 'green' | 'amber' | 'red' | string;
  remarks?: string;
  createdByAdmin?: boolean;
  editedByAdmin?: boolean;
  autoGenerated?: boolean;
  hasAttachment?: boolean;
  timestamp?: number;
  lastModifiedAt?: number;
  clockInLocation?: GeoLocationPoint;
  clockOutLocation?: GeoLocationPoint;
}

export interface LeaveRequest {
  id?: string;
  key?: string;
  empName: string;
  empId: string;
  userEmail: string;
  leaveType: 'annual' | 'medical' | 'emergency' | 'off' | string;
  startDate: string;
  endDate: string;
  reason: string;
  hasAttachment?: boolean;
  mcBase64?: string | null;
  mcFileName?: string | null;
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  createdAt?: string | number;
  appliedAt?: number;
}

export interface FlavorInventoryItem {
  prevStock: number;
  newStock: number;
  sold: number;
  promoFree: number;
  balance: number;
}

export interface SalesReportPayload {
  key?: string;
  submittedBy: string;
  userEmail: string;
  timestamp: number | object;
  totalDailySales: number;
  cawangan: string;
  date: string;
  jumlahBag: string;
  pettyCash: number;
  salesCash: number;
  platforms: {
    misi: number;
    lalamove: number;
    foodPanda: string;
    grabFood: number;
    shopeeFood: number;
  };
  expenses: {
    gas: number;
    ais: number;
    beliBarang: number;
    minyakKenderaan: number;
    dobi: number;
    minyakMasak: string;
    staffMeal: string;
  };
  qualityAndWastage: {
    ayamTakHabis: string;
    ayamBusuk: string;
    ayamShort: string;
    review: string;
    loyalKad: string;
    promo10Pcs: string;
  };
  catatan: string;
  inventoryTracker: Record<string, FlavorInventoryItem>;
}

export interface PayslipRecord {
  key: string;
  staffEmail: string;
  period: string; // YYYY-MM
  amount?: number | string;
  position?: string;
  fileData?: string; // base64
  contentType?: string;
  fileName?: string;
  createdAt?: number;
}
